[build]
  command = "./netlify-build.sh"
  publish = "dist"

# Define environment variables for the build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
# Define redirects for SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200