[build]
  command = "./netlify-build.sh"
  publish = "dist"
  functions = "netlify/functions"

# Define environment variables for the build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
# Define redirects for SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Redirect API calls to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200