[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"  # For serverless functions if needed in the future

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev" # This ensures dev dependencies are installed for the build process

# Asset optimization - improve performance
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200